### ISSUE TITLE
'NoPreviews' Not Functional

### ISSUE THREAD

**Issue by ltoddnelson** [kieranwalsh/PowerShell#2]
[https://github.com/kieranwalsh/PowerShell/tree/main/Update-AllPSModules](url)

Please clarify the use of the "NoPreviews" switch via an example.  Not working for me using "-NoPreviews" or  "-NoPreviews:$true" or  "-NoPreviews $true" or  "-NoPreviews true".

**Comment by kieranwalsh** [comment]
It's a switch, so "-NoPreviews" should be enough.
It basically ignores any "version" that includes a hyphen, so a version of "3.0.11-beta" will get ignored. What behaviour are you seeing and I'll try to replicate it.

**Comment by ltoddnelson** [comment]
PS C:\Scripts> .\Update-AllPSModules.ps1 -NoPreviews
C:\Scripts\Update-AllPSModules.ps1 : Missing an argument for parameter 'NoPreviews'.
Specify a parameter of type 'System.Management.Automation.ParameterAttribute' and try again.
At line:1 char:27
+ .\Update-AllPSModules.ps1 -NoPreviews
+                           ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-AllPSModules.ps1], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Update-AllPSModules.ps1

**Comment by ltoddnelson** [comment]
The script works fine without the switch not not with the switch.

**Comment by kieranwalsh** [comment]
Huh, yes, I'm getting that as well now. Must have made a typo somewhere. Thanks for pointing it out, I'll go through it now.

**Comment by ltoddnelson** [comment]
Once fixed, will you provide an example just so we are clear that the switch does or does not require a parameter.

This is a great tool that I've been struggling with trying to and finding time to create.  Thanks!

**Comment by kieranwalsh** [comment]
Ok, I've found the typo and uploaded a fix. I'll add comment-based help tonight, but in the meantime just using:
 .\Update-AllPSModules.ps1 -NoPreviews 
 should get it running.

**Comment by ltoddnelson** [comment]
It is functional now.  Thank you, again.

**Comment by kieranwalsh** [comment]
Excellent. Thanks for the feedback and I've now uploaded a version with comment-based help included.
